events/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.event_list, name='event_list'),
    path('<int:pk>/', views.participant_list, name='participant_list'),
]

home/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
# url for app
app_name = 'home'
urlpatterns = [
    path('', views.indexlogin, name='indexlogin'),
]

news/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import *

app_name = 'news'
urlpatterns = [
    path('', views.index, name='index'),
    path('view_news', views.view_news, name='view_news'),
]

register_member/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *

app_name = 'register_member'
urlpatterns = [
    url(r'^User', daftar_user, name='daftar_user'),
    url(r'^Register', message_post, name='message_post'),
    url(r'^Daftar', formsubmit, name='formsubmit'),
    url(r'^auth/', include('social_django.urls', namespace='social'))
]

registeredEvent/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'registeredEvent'
urlpatterns = [
    path('', index, name='index'),
    path('getRegisteredEvent', getRegisteredEvent, name='getRegisteredEvent'),
]

tp1/urls.py
from django.contrib import admin
from django.urls import path, include
import home.urls as home
import register_member.urls as register_member
import about.urls as about
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls'), name='home'),
    path('events/', include('events.urls'), name='events'),
    path('events/register/',
         include('register_event.urls'), name='register_event'),
    path('news/', include('news.urls'), name='news'),
    path('register_member/',include(register_member), name='register_member'),
    path('about/',include('about.urls'), name='about'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('logout/', home.views.logoutPage, name='logout'),
    path('registeredEvent/', include('registeredEvent.urls'), name='registeredEvent'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
# Create your views here.


def index(request):
    return render(request, 'index.html')
    
def logoutPage(request):
	request.session.flush()
	logout(request)
	return HttpResponseRedirect('/home/')

def indexlogin(request):
    if  request.user.is_authenticated :
        request.session['sessionkey'] = request.session.session_key
        request.session['email'] = request.user.email
        request.session['username'] = request.user.username
        request.session['fullname'] = request.user.first_name + " " + request.user.last_name
        request.session.modified = True
        print(request.session.items())
    return render(request,'indexlogin.html')

home/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

        <title>Student Union</title>
        <link rel='stylesheet' type='text/css' href="{% static " css/student-union.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static 'stylehome.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    </head>

    <body>
        <div class="img">
            <div class="container-fluid">
                <br><br>
                <div class="row">
                    <div class="col-md-12 col-sm-12 i1 w400 center">
                        <b>STUDENT UNION.</b>
                    </div>
                </div>
                <br><br>
                <div class="row">
                    <div class="col-md-1 col-sm-1"></div>
                    <div class="col-md-3 col-sm-3 i2 w200 center">
                        <a href="{% url 'news:index' %}">news</a>
                    </div>
                    <div class="col-md-4 col-sm-4 i2 w200 center">
                        <a href="{% url 'events:event_list' %}">event</a>
                    </div>
                    <div class="col-md-3 col-sm-3 i2 w200 center">
                        <a href="{% url 'register_member:formsubmit' %}">register</a>
                    </div>
                    <div class="col-md-1 col-sm-1"></div>
                </div>
                <br><br><br><br><br><br><br><br>
                <div class="row">
                    <div class="col-md-3 col-sm-3"></div>
                    <div class="col-md-6 col-sm-6 i3 w500 ibox center">
                        learn today, lead tomorrow
                    </div>
                    <div class="col-md-3 col-sm-3"></div>
                </div>
                <div class="row">
                    <br><br><br><br><br><br><br><br><br><br><br><br>
                    <a href="logout">Log Out</a>
                </div>
            </div>
        </div>
        {% block content %}{% endblock %}
    </body>

</html>

home/templates/indexlogin.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

        <title>Student Union</title>
        <link rel='stylesheet' type='text/css' href="{% static " css/student-union.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static 'stylehome.css' %}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    </head>

    <body>
        <div class="img">
            <div class="container-fluid">
                <br><br>
                <div class="row">
                    <div class="col-md-12 col-sm-12 i1 w400 center">
                        <b>STUDENT UNION.</b>
                        <br>
                        {% if user.is_authenticated %}
                            <b>Hello {{ user.first_name  }} {{ user.last_name }}</b>
                        {% endif %}
                    </div>
                </div>
                <br><br>
                <div class="row">
                    <div class="col i2 w200 center">
                        <a href="{% url 'news:index' %}">news</a>
                    </div>
                    <div class="col i2 w200 center">
                        <a href="{% url 'events:event_list' %}">event</a>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="col i2 w200 center">
                            <a href="{% url 'registeredEvent:index' %}">my events</a>
                        </div>
                    {% endif %}
                    <div class="col i2 w200 center">
                        {% if user.is_authenticated %}
                            <a href="{% url 'logout' %}">logout</a>
                        {% else %}
                        <a href="{% url 'register_member:formsubmit' %}">register</a>
                        {% endif %}    
                    </div>
                    <div class="col-md-1 col-sm-1"></div>
                </div>
                <br><br><br><br><br><br><br><br>
                <div class="row">
                    <div class="col-md-3 col-sm-3"></div>
                    <div class="col-md-6 col-sm-6 i3 w500 ibox center">
                        learn today, lead tomorrow
                    </div>
                    <div class="col-md-3 col-sm-3"></div>
                </div>
                <div class="row">
                    <br><br><br><br><br><br><br><br><br><br><br><br>
                </div>
            </div>
        </div>
        {% block content %}{% endblock %}
    </body>

</html>