about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('', views.testimonials, name='testimonials'),
    path('post/', views.post, name='post'),
]

tp1/urls.py
from django.contrib import admin
from django.urls import path, include
import home.urls as home
import register_member.urls as register_member
import about.urls as about
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls'), name='home'),
    path('events/', include('events.urls'), name='events'),
    path('events/register/',
         include('register_event.urls'), name='register_event'),
    path('news/', include('news.urls'), name='news'),
    path('register_member/',include(register_member), name='register_member'),
    path('about/',include('about.urls'), name='about'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('logout/', home.views.logoutPage, name='logout'),
    path('registeredEvent/', include('registeredEvent.urls'), name='registeredEvent'),
]

about/models.py
from django.db import models

# Create your models here.
class Testimonial(models.Model):
    name = models.CharField(max_length=200, blank=True)
    testimonial = models.CharField(max_length=300)
    date = models.DateField(auto_now_add=True)

about/forms.py
from django import forms
from .models import Testimonial

class TestimonialForm(forms.Form):
    attrs = {
        'class':'form-control',
        'id': 'post-text'
    }

    testimonial = forms.CharField(required=True, max_length=300, label='testimonial', widget=forms.Textarea(attrs=attrs))

about/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .forms import TestimonialForm
from .models import Testimonial
import requests, json


# Create your views here.
response = {}
@csrf_exempt
def post(request):
    if (request.method == "POST"):
        message = request.POST.get('the_post')
        if request.user.is_authenticated:
            if 'name' not in request.session:
                request.session['name'] = request.user.first_name + " " + request.user.last_name
        response['name'] = request.session['name']
        name = response['name']
        new = Testimonial.objects.create(name=name, testimonial=message)
        print(new.date)
        time = new.date.strftime("%b. %d, %Y")
        response['testimonial'] = message
        response['time'] = time
        return HttpResponse(json.dumps(response), content_type="application/json")
    else:
        return HttpResponse(json.dumps({"nothing": "failed"}), content_type="application/json")


def testimonials(request):
    response = {}
    testimonials = Testimonial.objects.all()
    data = TestimonialForm()
    return render(request, "about.html", {'form': data, 'testimonials': testimonials})

about/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container-fluid">
    <br><br><br>
    <div class="row text-center">
        <div class="col-md-3 col-sm-3"></div>
        <div class="col-md-6 col-sm-6">
            <p class="p1" style="font-size: 56px;"><b>ABOUT</b></p>
            <hr>
        </div>
        <div class="col-md-3 col-sm-3"></div>
    </div>

    {% if user.is_authenticated %}
    <div class="row text-center">
        <div class="col-md-12 col-sm-12">
            <p class="p4">leave your testimonials here</p>
        </div>
    </div>

    <div class="row text-center">
        <div class="col-md-2 col-sm-2"></div>
        <div class="col-md-8 col-sm-8">
            <section name="form">
                <br><br>
                <form id="post-form" method="POST" action="{% url 'about:post' %}">
                    {% csrf_token %}
                    {% for a in form %}
                    <div class="p3">{{ a }}</div>
                    {% endfor %}
                    <button type="submit" class="btn btn-default box p4" id="submit" action="{% url 'about:post' %}">submit</button>
                </form>
            </section>
        </div>
        <div class="col-md-2 col-sm-2"></div>
    </div>

    {% else %}
    <br><br><br><br><br><br>
    <div class="row text-center">
        <div class="col-md-2 col-sm-2"></div>
        <div class="col-md-8 col-sm-8">
            <div class="p4">You must login to write a testimonial!</div>
        </div>
        <div class="col-md-2 col-sm-2"></div>
    </div>
    <br>
    <div class="row text-center">
        <div class="col-md-12 col-sm-12">
            <a href="{% url 'social:begin' 'google-oauth2' %}">
                <button type="submit" class="btn btn-default box p4" id="submit">Login with google</button>
            </a>
        </div>
    </div>
    {% endif %}

    <div class="row p4">
        <div class="col-md-2 col-sm-2"></div>
        <div class="col-md-8 col-sm-8">
            <br><br><br><br>
            <p class="p2 center w400"><i>T E S T I M O N I A L S</i></p>
            <div id="result" style="font-size: 15px;">
                {% if testimonials %}
                    {% for data in testimonials %}
                        <div style="text-align: center"> {{data.name}}, {{data.date}} </div>
                        <div class="center" style="font-size: 25px;"> "{{data.testimonial}}" </div>
                        <br>
                    {%endfor%}
            {%else%}
                <div id="elseresult" class="p4 center">no testimonials :(</div>
            {%endif%}

        </div>
    </div>
</div>

<script>
    // Submit post on submit
    $('#post-form').on('submit', function (event) {
        event.preventDefault();
        console.log("form submitted")
        create_post();
    });

    function create_post() {
        console.log("create post is working")
        $.ajax({
            url: "post/",
            type: "POST",
            async: true,
            data: {
                'csrfmiddlewaretoken': "{{ csrf_token }}",
                the_post: $('#post-text').val()
            },

            success: function (json) {
                console.log($('#post-text').val())
                $('#post-text').val('');
                console.log(json.testimonial);
                console.log("success");
                $("#elseresult").html("");
                $("#result").append("<div class='center'>" + json.name + ", " + json.time + "</div>" +
                    "<div class='center' style='font-size: 25px;'>" + "\"" + json.testimonial + "\"" + "</div><br>");

                console.log("masuk sini");
            },

            error: function (xhr, errmsg, err) {
                $('#post-text').val('');
                console.log("something wrong happened");
            }
        });
    };
</script>

{% endblock %}