events/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.event_list, name='event_list'),
    path('<int:pk>/', views.participant_list, name='participant_list'),
]

register_event/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'register_event'
urlpatterns = [
    path('<int:pk>/', views.register_event, name='register_event'),
    path('<int:pk>/thankyou/', views.thankyou, name='thankyou'),
]

register_member/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import *

app_name = 'register_member'
urlpatterns = [
    url(r'^User', daftar_user, name='daftar_user'),
    url(r'^Register', message_post, name='message_post'),
    url(r'^Daftar', formsubmit, name='formsubmit'),
    url(r'^auth/', include('social_django.urls', namespace='social'))
]

tp1/urls.py
from django.contrib import admin
from django.urls import path, include
import home.urls as home
import register_member.urls as register_member
import about.urls as about
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls'), name='home'),
    path('events/', include('events.urls'), name='events'),
    path('events/register/',
         include('register_event.urls'), name='register_event'),
    path('news/', include('news.urls'), name='news'),
    path('register_member/',include(register_member), name='register_member'),
    path('about/',include('about.urls'), name='about'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('logout/', home.views.logoutPage, name='logout'),
    path('registeredEvent/', include('registeredEvent.urls'), name='registeredEvent'),
]

events/models.py
from django.db import models
from datetime import datetime
from register_event.models import Register
# from django.contrib.auth.models import User

# Create your models here.


class Events(models.Model):
    title = models.CharField(max_length=30)
    date = models.DateTimeField(default=datetime.now)
    description = models.CharField(max_length=3200)
    participants = models.ManyToManyField(Register, blank=True)

events/views.py
from django.shortcuts import render, redirect
from .models import Events
from django.contrib.auth import logout
from django.http import HttpResponseRedirect

def event_list(request):
    events = Events.objects.all().order_by('date')
    if request.user.is_authenticated:
        lst = []
        for i in events:
            checker = False
            for participant in i.participants.all():
                if request.user.email == participant.email:
                    checker = True
                    break
            lst.append({"event": i, "is_participate": checker})
        response = {'events': lst}
    else:
        lst = []
        for i in events:
            lst.append({"event": i})
        response = {'events': lst}
    return render(request, 'events.html', response)


def participant_list(request, pk):
    event = Events.objects.get(pk=pk)
    response = {'event': event}
    return render(request, 'participant_list.html', response)

events/templates/events.html
{% extends "base.html" %}
{% load static %}
{% block title%}Events List{% endblock %}
{% block content %}
    <div class="container">
        <h1 class="text-center  p1 w500">Events</h1>
        <br>
        <div class="bg-blue event ">
            {% for event in events %}
                <div class="row bg-light rounded">
                    <div class="col-sm-10">
                        <h3 class=" p1 w500">{{ event.event.title }}</h3>
                        <h6 class="lead">{{ event.event.date.date }}</h6>
                        <p class="text-justify font-weight-light lead">{{ event.event.description|truncatewords:50  }}</p>
                    </div>
                    <div class="col-sm-2 text-center  padding-top-10">
                        <br><br>
                        {% if user.is_authenticated %}
                            {% if event.is_participate %}
                                <button type="button" disabled="disabled" name="button" class="btn btn-default p6 text-black">Registered</button>
                            {% else %}
                                <a href="{% url 'register_event:register_event' event.event.pk %}" class="btn btn-default p4 text-black">+ Book</a><br>
                            {% endif %}
                        {% else %}
                            <a href="{% url 'register_member:formsubmit' %}" class="btn btn-default p4 text-black">Login</a><br>
                            <small>Login first before book</small>
                        {% endif %}
                        <br>
                        <a href="{% url 'events:participant_list' event.event.pk %}" class="btn btn-default p4 text-black">Details</a>
                    </div>
                </div>
                <br>
            {% endfor %}
        </div>
    </div>
{% endblock %}

events/templates/participant_list.html
{% extends "base.html" %}
{% load static %}

{% block title%}Details :
    {{ event.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <br><br>
        <div class="rounded bg-blue">
            <h1 id="p1" class="p1 w500">{{ event.title }}</h1>
            <article class="text-justify">{{ event.description }}</article>
        </div>
        <br><br><br>
        <div class="rounded bg-blue">
            <h3 id="p1" class="p1 w500">DAFTAR PESERTA</h3>
            {% if event.participants.all.count == 0 %}
                Belum ada Peserta
            {% else %}
                <div class="row">
                    {% for participant in event.participants.all %}
                        <div class="col-sm-3 text-center">
                            {{ forloop.counter }}.
                            {{ participant.user }}
                            <br>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}