about/urls.py
from django.urls import path
from . import views

app_name = 'about'
urlpatterns = [
    path('', views.testimonials, name='testimonials'),
    path('post/', views.post, name='post'),
]

events/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'events'

urlpatterns = [
    path('', views.event_list, name='event_list'),
    path('<int:pk>/', views.participant_list, name='participant_list'),
]

home/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
# url for app
app_name = 'home'
urlpatterns = [
    path('', views.indexlogin, name='indexlogin'),
]

news/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import *

app_name = 'news'
urlpatterns = [
    path('', views.index, name='index'),
    path('view_news', views.view_news, name='view_news'),
]

tp1/urls.py
from django.contrib import admin
from django.urls import path, include
import home.urls as home
import register_member.urls as register_member
import about.urls as about
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls'), name='home'),
    path('events/', include('events.urls'), name='events'),
    path('events/register/',
         include('register_event.urls'), name='register_event'),
    path('news/', include('news.urls'), name='news'),
    path('register_member/',include(register_member), name='register_member'),
    path('about/',include('about.urls'), name='about'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    path('logout/', home.views.logoutPage, name='logout'),
    path('registeredEvent/', include('registeredEvent.urls'), name='registeredEvent'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load static %}
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
		<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
		<link rel='stylesheet' type='text/css' href="{% static "css/student-union.css" %}">
		<link rel='stylesheet' type='text/css' href="{% static "css/style.css" %}">
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
		<link rel='stylesheet' type='text/css' href="{% static "css/news.css" %}">
		{% block css %}{% endblock %}
		<title>
			{% block title%}{% endblock %}
		</title>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		{% block javascript %}{% endblock %}
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	</head>
	<body>
		<nav class="navbar navbar-expand-sm navbar-light fixed-top">
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
				<div class="navbar-nav">
					<a class="nav-item nav-link" href="{% url 'home:indexlogin' %}">home</a>
					<a class="nav-item nav-link" href="{% url 'news:index' %}">news</a>
					<a class="nav-item nav-link" href="{% url 'events:event_list' %}">events</a>
					<a class="nav-item nav-link" href="{% url 'about:testimonials' %}">about</a>
					{% if user.is_authenticated %}
						<a class="nav-item nav-link" href="{% url 'registeredEvent:index' %}">my events</a>
						<a class="nav-item nav-link" href="{% url 'logout' %}">logout</a>
					{% else %}
						<a class="nav-item nav-link" href="{% url 'register_member:formsubmit' %}">sign up</a>
					{% endif %}
				</div>
			</div>
		</nav>
		{% block content %}{% endblock %}
	</body>
</html>